#!/usr/bin/env bash
#
#/ command: github:get-download: "Get a download from the specified repository"
#
#/ usage: rerun github:get-download [ --url <https://github.com>]  --owner <>  --repository <>  --file <> [ --output <>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: URL OWNER REPOSITORY FILE OUTPUT

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: github:get-download. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/get-download/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/get-download/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

[[ -z $OUTPUT ]] && OUTPUT=$FILE

curl -sfL -o $OUTPUT ${URL}/downloads/${OWNER}/${REPOSITORY}/${FILE}

exit $?

# Done
