#!/usr/bin/env bash
#
#/ command: github:delete-download: "Delete a download"
#
#/ usage: rerun github:delete-download  --file <>  --owner <>  --repository <> [ --force <false>] [ --authorization-file <$HOME/.rerun/github.authorization>] [ --api-url <https://api.github.com>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: FILE OWNER REPOSITORY FORCE AUTHORIZATION_FILE API_URL

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: github:delete-download. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/delete-download/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/delete-download/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}

# ------------------------------
# Your implementation goes here.
# ------------------------------

if ! DOWNLOAD=$(rerun github:list-downloads --owner $OWNER --repository $REPOSITORY | grep "^$FILE:")
then
  if [[ $FORCE = "true" ]]
  then
    exit 0
  else
    rerun_die "download file \"$FILE\" doesn't exist"
  fi
fi

ID=$(echo $DOWNLOAD | cut -d: -f3)

curl_github_api ${AUTHORIZATION_FILE} ${API_URL} DELETE /repos/${OWNER}/${REPOSITORY}/downloads/${ID}
echo "deleted $ID"

exit $?

# Done
