#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: github:delete-download: "Delete a download"
#/ usage: rerun github:delete-download  --file <>  --owner <>  --repository <> [ --force <false>] [ --authorization-file <$HOME/.rerun/github.authorization>] [ --api-url <https://api.github.com>] 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh delete-download || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: github:delete-download. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: FILE OWNER REPOSITORY FORCE AUTHORIZATION_FILE API_URL

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

if ! DOWNLOAD=$(rerun github:list-downloads --owner $OWNER --repository $REPOSITORY | grep "^$FILE:")
then
  if [[ $FORCE = "true" ]]
  then
    exit 0
  else
    rerun_die "download file \"$FILE\" doesn't exist"
  fi
fi

ID=$(echo $DOWNLOAD | cut -d: -f3)

curl_github_api ${AUTHORIZATION_FILE} ${API_URL} DELETE /repos/${OWNER}/${REPOSITORY}/downloads/${ID}
echo "deleted $ID"

exit $?

# Done
