#!/usr/bin/env bash
#
#/ command: github:list-repo-deploy-keys: "List repository deploy keys"
#
#/ usage: rerun github:list-repo-deploy-keys [ --url <https://api.github.com>]  --owner <>  --repository <> [ --api-url <https://api.github.com>] [ --authorization-file <$HOME/.rerun/github.authorization>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: URL OWNER REPOSITORY API_URL AUTHORIZATION_FILE

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: github:list-repo-deploy-keys. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/list-repo-deploy-keys/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/list-repo-deploy-keys/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

githubCurlAPI ${AUTHORIZATION_FILE} ${API_URL} GET /repos/${OWNER}/${REPOSITORY}/keys | jq -r '.response | .[] | .title + ":" + (.id | tostring)'

exit $?

# Done
