# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov 20 23:24:37 PST 2012
#
#/ usage: github:create-download [ --content-type <application/x-rpm>] [ --description|-d <>]  --file <>  --owner <>  --repository <> [ --authorization-file <$HOME/.rerun/github.authorization>] [ --api-url <https://api.github.com>] [ --force <false>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --content-type) rerun_option_check $# ; CONTENT_TYPE=$2 ; shift ;;
            --description|-d) rerun_option_check $# ; DESCRIPTION=$2 ; shift ;;
            --file) rerun_option_check $# ; FILE=$2 ; shift ;;
            --owner) rerun_option_check $# ; OWNER=$2 ; shift ;;
            --repository) rerun_option_check $# ; REPOSITORY=$2 ; shift ;;
            --authorization-file) rerun_option_check $# ; AUTHORIZATION_FILE=$2 ; shift ;;
            --api-url) rerun_option_check $# ; API_URL=$2 ; shift ;;
            --force) rerun_option_check $# ; FORCE=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$CONTENT_TYPE" ] && CONTENT_TYPE="application/x-rpm"
    [ -z "$AUTHORIZATION_FILE" ] && AUTHORIZATION_FILE="$HOME/.rerun/github.authorization"
    [ -z "$API_URL" ] && API_URL="https://api.github.com"
    [ -z "$FORCE" ] && FORCE="false"
    # Check required options are set
    [ -z "$FILE" ] && { echo >&2 "missing required option: --file" ; return 2 ; }
    [ -z "$OWNER" ] && { echo >&2 "missing required option: --owner" ; return 2 ; }
    [ -z "$REPOSITORY" ] && { echo >&2 "missing required option: --repository" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
CONTENT_TYPE=
DESCRIPTION=
FILE=
OWNER=
REPOSITORY=
AUTHORIZATION_FILE=
API_URL=
FORCE=


