# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Oct 29 15:22:04 PDT 2012
#
#/ usage: github:create-download [ --content-type|-c <application/zip>] [ --description|-d <>]  --file|-f <>  --owner|-o <>  --repository|-r <> [ --url|-u <https://api.github.com>] 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [content-type description file owner repository url]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --content-type|-c) rerun_option_check $# ; CONTENT_TYPE=$2 ; shift ;;
        --description|-d) rerun_option_check $# ; DESCRIPTION=$2 ; shift ;;
        --file|-f) rerun_option_check $# ; FILE=$2 ; shift ;;
        --owner|-o) rerun_option_check $# ; OWNER=$2 ; shift ;;
        --repository|-r) rerun_option_check $# ; REPOSITORY=$2 ; shift ;;
        --url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$CONTENT_TYPE" ] && CONTENT_TYPE="application/zip"
[ -z "$URL" ] && URL="https://api.github.com"
# Check required options are set
[ -z "$FILE" ] && { echo >&2 "missing required option: --file" ; return 2 ; }
[ -z "$OWNER" ] && { echo >&2 "missing required option: --owner" ; return 2 ; }
[ -z "$REPOSITORY" ] && { echo >&2 "missing required option: --repository" ; return 2 ; }
# If option variables are declared exportable, export them.

#
return 0
