#!/usr/bin/env bash
#
#/ command: github:list-downloads: "List downloads for a repository"
#
#/ usage: rerun github:list-downloads  --owner <>  --repository <> [ --url <https://api.github.com>] [ --content-type <application/x-rpm>] [ --latest <false>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: OWNER REPOSITORY URL CONTENT_TYPE LATEST

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: github:list-downloads. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/list-downloads/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/list-downloads/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}

# ------------------------------
# Your implementation goes here.
# ------------------------------

RESPONSE=$(mktemp)

# List the downloads.
curl -s ${URL}/repos/${OWNER}/${REPOSITORY}/downloads > ${RESPONSE}

# Check for an API call error.
if [[ $(cat ${RESPONSE} | jq -r '.[]') = "Not Found" ]]
then
  rerun_die "either the owner or the repository was not found"
fi

# Display the names and identifiers.
if [[ $LATEST = "false" ]]
then
  cat ${RESPONSE} | jq -r '.[] | .name + ":" + .content_type + ":" + (.id | tostring)' | grep ":${CONTENT_TYPE}:" | sort -nt: -k3
else
  cat ${RESPONSE} | jq -r '.[] | .name + ":" + .content_type + ":" + (.id | tostring)' | grep ":${CONTENT_TYPE}:" | sort -nt: -k3 | tail -1
fi

rm -f ${RESPONSE}

exit $?

# Done
